---
# https://github.com/geerlingguy/ansible-role-docker/blob/master/tasks/main.yml

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  notify: restart docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install Docker python module
  pip:
    name: docker
    state: present

- include_tasks: docker-users.yml
  when: docker_users | length > 0
