# Idea from: https://github.com/progmaticltd/homebox/blob/dev/config/system-example.yml

---
users:
  borja:
    name: Borja Sanchidrian

system:
  base_path: "/etc/homeserver"
  timezone: "Europe/Madrid"
