---
- name: Install sudo
  apt:
    name: sudo
    state: present

- name: Add users to sudo group
  user:
    name: "{{ item }}"
    groups: sudo
    append: true
  when: sudo_users | length > 0
  with_items: "{{ sudo_users }}"
